services:
  imigresen-api:
    image: clojure
    command: sh -c "cd /skulpture-eventing && lein install && cd /imigresen-common && lein install && cd /imigresen-api && lein test"
    volumes:
      - .:/imigresen-api
      - ../imigresen-common:/imigresen-common
      - ../skulpture-eventing:/skulpture-eventing
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      JAVA_ENV: "test"
