networks:
  default:
    name: imigresen
    driver: overlay
    attachable: true

secrets:
  proxy.certificate:
    file: ${PROXY_CERT_PATH}
  proxy.key:
    file: ${PROXY_KEY_PATH}

services:
  proxy:
    image: traefik:v3.4
    ports:
      - target: 80
        published: 80
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
    command: >
      --providers.swarm.endpoint=unix:///var/run/docker.sock
      --providers.swarm.exposedByDefault=false
      --providers.file.directory=/traefik
      --providers.file.watch=true
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
      --entryPoints.websecure.asDefault=true
      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/traefik
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    ulimits:
      nofile:
        soft: 20000
        hard: 20000

  imigresen-api-dev:
    image: skulpture/imigresen-api:dev
    # environment:
    #   LOG_LEVEL: ${LOG_LEVEL}
    #   OTEL_SERVICE_NAME: imigresen-api-dev
    #   GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID_DEV}
    #   GSHEETS_SPREADSHEET_ID: ${GSHEETS_SPREADSHEET_ID_DEV}
    #   ENABLE_TELEMETRY: "${ENABLE_TELEMETRY}"
    #   OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
    #   POSTMARK_TEMPLATE: ${POSTMARK_TEMPLATE_DEV}
    #   POSTMARK_SERVER_TOKEN: ${POSTMARK_SERVER_TOKEN}
    #   POSTMARK_ACCOUNT_TOKEN: ${POSTMARK_ACCOUNT_TOKEN}
    #   GO_ENV: "development"
    deploy:
      mode: replicated
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.http.routers.imigresen-api-dev.rule: Host(`imigresen-api-dev.skulpture.xyz`)
        traefik.http.routers.imigresen-api-dev.tls.domains.main: skulpture.xyz
        traefik.http.routers.imigresen-api-dev.tls.domains.sans: "*.skulpture.xyz"
        traefik.http.services.imigresen-api-dev-service.loadbalancer.server.port: 80
        traefik.http.services.imigresen-api-dev-service.loadbalancer.server.scheme: http
        traefik.http.services.imigresen-api-dev-service.loadbalancer.healthcheck.path: /ping
        traefik.http.services.imigresen-api-dev-service.loadbalancer.healthcheck.status: 200
        traefik.swarm.lbswarm: "true"
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/ping || exit 1" ]
      interval: 1m30s
      timeout: 1m
      retries: 5
      start_period: 30s

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel/collector-config.yml:/etc/otelcol-contrib/config.yaml
    deploy:
      mode: replicated
      replicas: 1
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_AUTH_TOKEN: ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}
