name: Buang preview deployment

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  BUANG_API_BASE_URL: 'https://preview.imigresen.skulpture.xyz'
  BUANG_API_KEY: ${{ secrets.BUANG_API_KEY }}
  BUANG_PROJECT_ID: ${{ vars.BUANG_PROJECT_ID }}
  CREATE_DEPLOYMENT_BRANCH: ${{ github.head_ref }}

jobs:    
  buang-preview:
    runs-on: ubuntu-latest

    steps:
      - id: buang_deployment
        name: Buang deployment
        run: |
          curl -X DELETE '${{ env.BUANG_API_BASE_URL }}/api/v1/project/${{ env.BUANG_PROJECT_ID }}/branch' -H 'X-API-KEY: ${{ env.BUANG_API_KEY }}' -H 'Content-Type: application/json'
