name: Build and Publish Storybook to GitHub Pages

on:
  pull_request_target:
    branches: [master, staging, dev]
  push:
    branches: [master, staging, dev]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Storybook
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        working-directory: ./client
        run: npm install -g corepack@latest && corepack pnpm install && corepack pnpm build-storybook

      - name: Build and publish Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        if: github.event_name == 'push'
        with:
          install_command: cd ./client && npm install -g corepack@latest && corepack pnpm install # default: npm ci
          build_command: corepack pnpm build-storybook # default: npm run build-storybook
          path: ./client/storybook-static # default: dist/storybook
          checkout: false # default: true
