name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - master
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./client

jobs:
  deploy:
    if: github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install # default: npm ci
          build_command: pnpm build-storybook # default: npm run build-storybook
          path: storybook-static # default: dist/storybook
          checkout: false # default: true
