name: Build and Publish Storybook to GitHub Pages

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build Storybook
        if: github.event.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        working-directory: ./client
        run: corepack pnpm install && corepack pnpm build-storybook

      - name: Build and publish Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        if: github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          install_command: cd ./client && corepack pnpm install # default: npm ci
          build_command: corepack pnpm build-storybook # default: npm run build-storybook
          path: ./client/storybook-static # default: dist/storybook
          checkout: false # default: true
