name: Test services

on:
  push:
    branches: [master, staging, dev]
  pull_request:
    branches: [master, staging, dev]
  workflow_dispatch:

jobs:
  test-eventing:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Test API
        working-directory: api/skulpture-eventing
        run: |
            docker compose -f docker-compose.test.yml up --exit-code-from skulpture-eventing

  test-common:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Test API
        working-directory: api/imigresen-common
        run: |
            docker compose -f docker-compose.test.yml up --exit-code-from imigresen-common

  test-api:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Test API
        working-directory: api/imigresen-api
        run: |
            docker compose -f docker-compose.test.yml up --exit-code-from imigresen-api
