services:
  skulpture-eventing:
    image: clojure
    command: >
      sh -c "
      cd /skulpture-eventing && lein cljfmt check && lein test"
    volumes:
      - .:/skulpture-eventing
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      JAVA_ENV: "test"
